[package]
name = "nsqute"
version = "0.1.0"
authors = ["Xavier Perez <xperez@fastly.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "*"
bytes = "*"
crossbeam-channel = "*"
